### ISSUE TITLE
Method my_fire_event? returning NoMethodError with events that not exist.

### ISSUE THREAD

**Issue by passalini** [aasm/aasm#128]
When I try

``` ruby
  object.aasm.may_fire_event? :unknown_event
```

It returns

``` ruby
  NoMethodError: undefined method `may_fire?' for nil:NilClass
```

I think that should return `false` or raise an error saying that event not exists

**Comment by pjmartorell** [comment]
> Actually the method `may_fire_event?` is not part of the documented (and public) DSL to be used for _AASM_. Why do you use this method? Its behaviour or name can change at any time.

Regarding this comment, I think that **public** methods are intended to be used by end users and not prone to change. If it's meant to be an internal method it should be a private method.

I have the same error with `fire!`, but seems that the implementation has changed quite a bit. Now it raises a `NoMethodError (undefined method `fire_callbacks' for nil:NilClass)`, and that means it tries to fire before callbacks even not knowing that the event exists, which is not the expected behaviour.

For me `fire` and `fire!`with an unknown event should not fire callbacks and return an exception like "Unknown event".
