### ISSUE TITLE
How to transition to next state? "user.next_state!" 

### ISSUE THREAD

**Issue by kibaekr** [aasm/aasm#174]
Is there a single method I can use to allow a user to transition into the next state, using a method like "user.next_state!" ? I know there could be more than one potential states you can transition into from a state, but maybe it would just go to the first one defined by default

**Comment by rdetert** [comment]
I'm not sure how this is even really possible. I'm coding this part right now and I've made my own `next_state!` method which is just a series of if-then statements. This only really works for a simple linear graph with no loops like I have in my current app. Otherwise it will just get overly complicated.

**Comment by alto** [comment]
@bigtunacan @maletor @rdetert I agree.

Closing (and denying) this feature request. Sorry @kibaekr !
