### ISSUE TITLE
Initial State Not Calling Enter on Create

### ISSUE THREAD

**Issue by ksylvest** [aasm/aasm#210]
Given the following code snippet:

    aasm column: :status do
      state :pending, enter: -> (user) { ... }, initial: true
      state :approved, enter: -> (user) { ... }

      event :approve do
        transition from: :pending, to: :approved
      end
    end

Running the following doesn't seem to trigger the `enter` callback for `pending`?

    model = Model.create # doesn't call the enter callback for pending
    model.approve # calls the enter callback for approved

Is this a regression? It looks like this may have been at one point resolved: http://rubyist.lighthouseapp.com/projects/13207/tickets/6-fails-to-execute-initial-state-callbacks

**Comment by alto** [comment]
@ksylvest Which version of _AASM_ are you using? Are you using _ActiveRecord_?

**Comment by ksylvest** [comment]
@alto v4.0.8. Yes (AR).

**Comment by alto** [comment]
@ksylvest Interesting, the lighthouse ticket goes back to 2008. I took over maintaining __AASM_ in 2011 (from version `2.2.1`), and the described behaviour (not calling callbacks for the initial state) was in place even then. I personally think, that this behaviour is correct, since you are actually not entering the initial state. You are already _in_ it when initialising the object.

Which version are you updating from? So, which was the last version that worked fine for you?

**Comment by ksylvest** [comment]
I'm not upgrading but kind of expected it to fire. I can see how it is somewhat ambiguous if a FSM should fire on enter but when Googling around the Lighthouse was the first result (mentioning the functionality worked in the opposite manner).

**Comment by alto** [comment]
I see. I would like to go with the current way. Can I close this ticket then?

**Comment by ksylvest** [comment]
Yup.

**Comment by alto** [comment]
Cheers!
