### ISSUE TITLE
Not using may_xxxx? correctly?

### ISSUE THREAD

**Issue by daveharris** [aasm/aasm#216]
Hi,

I have a requirement that if the state transitions from failed -> validated, there must be a user provided reason.
I have this aasm definition:

```ruby
aasm column: 'efd_state' do
  state :unvalidated, initial: true
  state :failed
  state :validated

  event :unvalidate do
    transitions to: :unvalidated
  end

  event :fail do
    transitions to: :failed
  end

  event :validate do
    transitions from: :failed, 
                to: :validated, 
                if: [:has_efd_state_forced_reason?]

    transitions from: [:calculate, :unvalidated, :validated], 
                to: :validated
  end
end

def has_efd_state_forced_reason?
  puts "Inside has_efd_state_forced_reason?: #{self.efd_state_forced_reason.present?}"
  self.efd_state_forced_reason.present?
end
```

This all works fine when using `validate!`, however the transition goes through when it's being updated via `update_attributes`. Unfortunately, the state needs to come from a select dropdown, so it must use  `update_attributes` rather than a special route in [this StackOverflow question](http://stackoverflow.com/a/6582186).

 Looking at #122 , I see it's suggested to use a `validate` block using `may_xxxx?`.

So I've added:

```ruby
validate do
  puts "From: #{self.aasm.from_state}"
  puts "To: #{self.aasm.to_state}"
  puts "may_validate?: #{self.may_validate?}"
  unless may_validate?
    errors.add(:efd_state, 'Requires EFD state forced reason when transitioning from failed to validated')
  end
end
```

However, this them seems to be the normal `event!` methods. It seems that the `may_validate?` always returns false when the transitioning *to* (not *from*) state is 'failed'. Huh??!!

```ruby
ds.efd_state   
# => "validated"
> ds.validate!
From: validated
To: validated
may_validate?: true
=> true
> ds.unvalidate!
From:   # Notice that aasm.from_state is empty....
To: unvalidated
may_validate?: true
=> true
> ds.fail!
From:
To: failed
Inside has_efd_state_forced_reason?: false
may_validate?: false
Inside has_efd_state_forced_reason?: false
=> false
```

I don't understand why `may_validate?` returns false if the to state is failed.

A bigger question is how *should* this be integrated with a controller using `ds.update_attributes(efd_state: 'failed')`

Any help would be greatly appreciated. Sorry for such a long message!

Thanks,

Dave

**Comment by alto** [comment]
Hi @daveharris,

Regarding your first question, there is no transition from `:failed` to `:failed`. Any `may_xxxx?` call asks for such a transition, which is why `may_validate?` returns `false`, always.

Why is it like that (and this touches your second question)? _AASM_ is designed around state machine semantics, so there are things like _states_, _transitions_ and _events_. Directly accessing (setting, overwriting) the state is up to the developer and _AASM_ doesn't prevent the developer from doing this. By this, unfortunalely, and as a side effect, _AASM_ itself is not designed to support direct state setting from a form presented to the user.

Using the `may_xxxx?` call in validations is a nice workaround for this, but then you have to make sure that there are transitions from any state to itself (if the user is allowed to select any state from the list).

I hope that helps to clarify the issue behind it.

Thorsten

**Comment by daveharris** [comment]
Hi,
Thanks for getting back to me. As the user could set the state to any state it wasn't really a state machine anyway and I felt like I was swimming against the tide and making hard for myself so I just used a normal attribute with active_model validations instead.

Thanks for the comment about needing a state transition to itself, that makes a lot of sense now.

Thanks for your advice - I realise that a state machine doesn't really fit into a web form.

Dave
