### ISSUE TITLE
Do transitions lock models?

### ISSUE THREAD

**Issue by rschooley** [aasm/aasm#230]
I am reading an article from someone at Engine Yard that talks about adding concurrency to aasm.  The article was written 5 years ago; is it still necessary to add this behavior in to aasm?

ref:
http://rhnh.net/2010/07/05/acts-as-state-machine-is-not-concurrent

**Comment by alto** [comment]
No, _AASM_ does not lock the database table row. I think it's overhead and not the responsibility of a state machine. _AASM_ operates on a loaded (fetched) object from the database and writes back its new state. In order to cover that concurrency problem, _AASM_ would need to lock the row, re-fetch the current state from the database, set the new state (or fail if the transition is not allowed anymore, because the tractor has been sold in the meantime), and release the lock.

The issue – as can be seen – is easy to solve in your controller (by setting up a transaction before loading the data from the database).
