### ISSUE TITLE
Is there a way to do a next ? 

### ISSUE THREAD

**Issue by chivoX** [aasm/aasm#314]
I have been reading through the code and it seems like there is now a way to do something like this

```
class Job
  include AASM

  aasm do
    state :sleeping, :initial => true
    state :running
    state :cleaning

    event :run do
      transitions :from => :sleeping, :to => :running
    end

    event :clean do
      transitions :from => :running, :to => :cleaning
    end

    event :sleep do
      transitions :from => [:running, :cleaning], :to => :sleeping
    end
  end

end

job = Job.new
job.status # => sleeping
job.next! 
job.status # => running
job.next!
job.status # => cleaning
job.next! # => false

```

this would trigger the run event, and if i send that message again that would trigger the next event.

**Comment by hspazio** [comment]
hi @chivoX, I've initially thought about the same when I started using _aasm_ but I figured that the power of this gem is that it implements a Non Deterministic State Machine so at a specific state you can have even 2 or more transitions to other states.
The `next!` method would be typical of a Determinitstic State Machine where there is only 1 possible transition at the time. In the example above if you are in `:running` state you are in a Non Deterministic workflow because you can transition either to `:cleaning` or to `:sleeping`. 
What should `:next!` method do in this case?

**Comment by chivoX** [comment]
i have been thinking about your question a bit.

since i sometimes find it hard to explain what i want to do ill do an example using something i used to get around in the meantime

def next!
   send(status_event_mapping[status.to_sym])
end

def status_event_mapping
   {
      request_sent: :send_email!,
      email_sent: :settle!,
      settling: bank!,
      banking: :clear!
    }
end

this is what in my case did what i needed, but i know this could be helpful for others too. 

what im doing is depending on the status trigger the right event.

**Comment by alto** [comment]
@chivoX No, there is no support for `next` in _AASM_, because – as @hspazio pointed out – it supports non-deterministic state machines, and _AASM_ can't guess what you want to do. But _AASM_ allows you to define a single event named `next` and define what shall be done on your behalf. Something like this:

```ruby
class Job
  include AASM

  aasm do
    state :request_sent, :initial => true
    state :email_sent
    state :settling
    state :banking
    state :cleared

    event :next do
      transitions :from => :request_sent, :to => :email_sent
      transitions :from => :email_sent, :to => :settling
      transitions :from => :settling, :to => :banking
      transitions :from => :banking, :to => :cleared
    end
  end

end
```

**Comment by davingee** [comment]
it would be nice to allow priority of states and then next would figure out the next available state based on the priority. this would allow Non Deterministic however the ability to just say next and if the guard passes it moves to the next state that it is allowed to move based on priority
