### ISSUE TITLE
NameError: uninitialized constant Model::AASM (rails 5.0.2)

### ISSUE THREAD

**Issue by thib44** [aasm/aasm#473]
Hello, I have an error only in rails console :

`NameError: uninitialized constant Partner::AASM`

And my model :
```ruby
class Partner < ApplicationRecord
  include AASM
  aasm do
    state :request, initial: true
    state :accept
    state :refused
    state :deleted

    event :accept do
      transitions from: :request, to: :accept
    end

    event :refuse do
      transitions from: :request, to: :refused
    end

    event :delete do
      transitions from: :accept, to: :deleted
    end
  end
end
```

I have not seen any solution on google...

**Comment by thib44** [comment]
I don't have problem when I replace `gem aasm` with `gem 'aasm', '~> 4.12'` in my gemfile

**Comment by darrenterhune** [comment]
rails 5.0.1
aasm 4.12
spring 2.0.0

@thib44 curious as to how that solved your problem. Since the latest release is 4.12 and `gem aasm` would install the latest unless you have some dependancy lock, that installs an earlier version of `aasm`. Do you know what version is actually installed in your bundle?

I had this same issue. But I've got `gem 'aasm', '~> 4.12'` set in my Gemfile. However I found this post: https://stackoverflow.com/questions/43571431/nameerror-uninitialized-constant-orderaasm which says commenting out the gem `spring` in your Gemfile will help debug, which does fix the issue for me to run `rails console`. Problem is that's not really a solution.

However, upgrading spring to version 2.0.2 does fix the problem 😄

**Comment by feliperaul** [comment]
I had the same issue and Spring was the culprit, and I was already on 2.0.2. Anyways, if you get this error in your rails console (my issue started after switching to a branch that didn't have AASM and coming back), just run ` bin/spring stop` and then `rails c` (the latter will automatically re-start spring).

**Comment by solaleye** [comment]
Thanks, @thib44! Got blocked with the same error and your solution helped!! 💯

**Comment by xofred** [comment]
For me, it's not a spring issue. I have to `require 'aasm'` in the model.

Our company's legacy projects have a strange setup. All the 'common' stuff like models are in a separated gem. Then it is required by several rails applications. So I have to add aasm in the gem's gemspec, rather than in the rails application.
