### ISSUE TITLE
change AASM state through edit action

### ISSUE THREAD

**Issue by mihir-kumar-thakur** [aasm/aasm#510]
I'm using AASM to manage states in my User model.

I want to change the status through the edit action.

To do this I'm using the method User.aasm_states_for_select in my form to populate the select input for states. When I hit the button commit all the changes are saved, including the state name. But the AASM event for that state is not called, it is happening because only the field status has changed and the event method has not been called.

Does anyone have a solution for my problem?
Thanks

**Comment by anuj-verma** [comment]
Hi @thakurmihir,

Giving select options for `states` is not a recommended approach because one `state` can be reached from multiple events. In below example `state` `open` can be reached from two events `verify` and `restart`.
```
event :verify do
  transitions :from => :unverified, :to => :open
end

event :restart do
  transitions :from => [:blocked, :resolved], :to => :open
end
```
So if your `state` options are `[:unverified, :open, :blocked, :resolved]`, and if someone selects `open` then you cannot determine the `event` from which your transition is happening.

I suggest you to populate your inputs with `permitted events` of `user` at his `current aasm state`. Refer: https://github.com/aasm/aasm#inspection

Using the above method,  in `controller` you can check the `event` and then accordingly invoke the event on `user` object.

**Comment by timlawrenz** [comment]
@mihir-kumar-thakur does the approach as suggested above work? Can this issue be closed?

**Comment by mihir-kumar-thakur** [comment]
@timlawrenz Thank you. It worked.
