### ISSUE TITLE
undefined method `aasm_state'

### ISSUE THREAD

**Issue by chintanparikh** [aasm/aasm#511]
I'm currently upgrading aasm from 4.0.8 to 4.12.3 as I need support for multiple state machines in one model. However, now all my tests give me ```undefined method `aasm_state' for #<ModelName:0x007f9ea46ebe10>```

I use aasm in almost all my models, but I don't ever use the default ```aasm_state``` column name. In most cases, my column is called ```state```, but in some models is called ```status``` or ```buyer_state```.

My definitions look like:
```
aasm :state, column: :state do
  # states and transitions go here
end
```
If I remove the name from the `aasm` call, like so:
```
aasm column: :state do
  # states and transitions go here
end
```
I get a different error -
```
     ActiveRecord::RecordInvalid:
       Validation failed: State is invalid
```
This one I understand - it happens because somewhere in the code there's a validation that looks up the allowable states by name - if there's no name it returns an empty array and thus we get the failed validation.

Any idea what's going on?

**Comment by davidenko87** [comment]
`column: :state` should be `column: 'state' ` then the error is fixed

**Comment by darrenterhune** [comment]
@chintanparikh does @davidenko87 solution fix your problem? If so please close.

**Comment by anilmaurya** [comment]
@chintanparikh Please reopen if you are still facing issues.

**Comment by skorth** [comment]
Maybe its related https://github.com/aasm/aasm/issues/443

Hey, we also run into the issue (undefined method `aasm_state') and found the reason why it happened **in our context**. We didn't have a default state_machine but AASM::StateMachineStore generates a default one for you if you call it for example by using ```Car.aasm.human_event_name(some_attribute)```.

In our case this happend while rendering the view. As you can see we forgot to add the state_machine name ```Car.aasm(:our_state_machine).human_event_name(some_attribute)```. The problem is that ```AASM::StateMachineStore``` internally creates a default one that can't work because we didn't have configured a default one. And since it works like a singleton we also had to restart the server afterwards.
