### ISSUE TITLE
❓Can `binding_event` be used to bind/trigger an event in the same state machine

### ISSUE THREAD

**Issue by ebouchut** [aasm/aasm#805]
The [example for `binding_event`](https://github.com/aasm/aasm#binding-event) suggests that it should be used to bind/trigger an event in a **different** state.
I am wondering if I can use it to bind an event from the **same** state machine.
For instance, in the contrived example below: bind the `start` event to the `pause` event. 

```ruby
class Example
  include AASM

  aasm do
    state :sleeping, initial: true
    state :started
    state :paused
    state :working
    state :stopped

    event :start, binding_event: pause do
      transitions from: :sleeping, to: :started
    end
    event :pause do
      transitions from: [:started, :working], to: paused 
    end
    event :stop do
      transitions from: [:started, :paused], to: :stopped
    end
    event :work do
      transitions from: :paused, to: :working
    end
    event stop do
      transitions from: :working, to: :stopped
    end

   #...
  end
end
```

CC @leanhdaovn for visibility.

**Comment by ccartano** [comment]
Wouldnt the ability to bind to the same state machine just null the use for a state? 
In your example, the event start would be called `foo.start!`and would transition from `sleeping` to `start` (but not save, and not creating a time stamp because of the binding), then immediately going to `pause` then saving. Im fairly certain a binding event will fire before the commit action. 

If you wanted to do such a call then you could accomplish it with 
```ruby
foo.start!
foo.pause!
```

or you could change your state machine to accept `:pause` from `:sleeping` and skip the start call
```ruby
event :pause do
  transitions from: [:started, :paused, :working], to: :paused
end
```

**Comment by ebouchut** [comment]
Thx @ccartano.
